### ISSUE TITLE
broken image link in README

### ISSUE THREAD

**Issue by hackedy** [the-lambda-church/coquille#28]
I'm getting a 404 from https://camo.githubusercontent.com/1353f36d9dde1d89936984603b3fdcd22ffc5c91/687474703a2f2f3139352e3135342e3138382e33332f2537457472656669732f636f7175696c6c652e706e67

**Comment by hackedy** [comment]
Oh, wait. It seems like github tries to cache images but the original server you link to in the readme is gone?

In any case, a link somewhere is dead.

**Comment by fotanus** [comment]
he is dead, Jim.

**Comment by fotanus** [comment]
Found this image

![coquille](http://www.zoppelt.net/assets/coq-vim.png)

Not sure if is the right one?

I installed it and at least for me the highlight interpreted won't work. Is this a supported feature? If yes, I can open other issue for it.

**Comment by gergo-** [comment]
The highlighting didn't work for me either. The problematic lines are:

    hi CheckedByCoq ctermbg=17 guibg=LightGreen
    hi SentToCoq ctermbg=60 guibg=LimeGreen

in the `coquille#Register()` function in `autoload/coquille.vim`. My particular combination of terminal and vim seems to simply ignore those background color numbers. This works for me:

    hi CheckedByCoq ctermbg=DarkGray guibg=LightGreen
    hi SentToCoq ctermbg=DarkMagenta guibg=LimeGreen

(I chose gray because vim's DarkBlue was still too garish for me.)

**Comment by fotanus** [comment]
@gergo- thanks a milion! It works for me.
